[MIG] crm_claim_rma
OCA/rma pull request #128
Opened 2017-10-24 20:17 UTC by max3903

2017-11-14 10:53 UTC, flotho commented
Hi everyone,
This one seems to be blocked. Any chance to be reviewed?

regards

2017-11-21 13:51 UTC, flotho commented
Still  blocked?

2017-11-25 11:15 UTC, max3903 commented
@flotho #126 needs to be merged first.

2018-01-11 11:16 UTC, DipSwitch commented
I merged `crma_claim_rma_code` and this module in my source code, howerver I get the following error when I'm trying to install the plugin:

	ParseError: "Error while validating constraint

	Element '<xpath expr="//button[@name='action_invoice_cancel']">' cannot be located in parent view

	Error context:
	View `invoice.form.cancel.inherit`
	[view_id: 1064, xml_id: account_cancel.invoice_form_cancel_inherit, model: account.invoice, parent_id: 725]
	None" while parsing /opt/odoo/custom/addons/crm_claim_rma/views/account_invoice.xml:5, near
	<record id="invoice_form" model="ir.ui.view">
			<field name="name">crm_claim_rma.invoice_form</field>
			<field name="model">account.invoice</field>
			<field name="inherit_id" ref="account.invoice_form"/>
			<field name="priority" eval="16"/>
			<field name="arch" type="xml">
				<data><field name="origin" position="after"/>

				<xpath expr="//button[@name='action_invoice_cancel']" position="replace">
					<field name="claim_id" attrs="{'invisible':[('type','!=','out_refund')]}"/>
				</xpath>

			</data></field>
		</record>

What I don't understand because when I look at the view it is as followed:

	<?xml version="1.0"?>
	<form string="Invoice">
                <header>
                    <button name="action_invoice_sent" type="object" string="Send by Email" attrs="{'invisible':['|',('sent','=',True), ('state', '!=', 'open')]}" class="oe_highlight" groups="base.group_user"/>
                    <button name="invoice_print" string="Print" type="object" attrs="{'invisible':['|',('sent','=',True), ('state', '!=', 'open')]}" class="oe_highlight" groups="base.group_user"/>
                    <button name="action_invoice_sent" type="object" string="Send by Email" attrs="{'invisible':['|',('sent','=',False), ('state', '!=', 'open')]}" groups="base.group_user"/>
                    <button name="invoice_print" string="Print Invoice" type="object" attrs="{'invisible':['|',('sent','=',False), ('state', '!=', 'open')]}" groups="base.group_user"/>
                    <button name="300" type="action" states="open" string="Register Payment" groups="account.group_account_invoice" class="oe_highlight"/>
                    <button name="action_invoice_open" type="object" states="draft" string="Validate" class="oe_highlight" groups="account.group_account_invoice"/>
                    <button name="action_invoice_open" type="object" states="proforma2" string="Validate" groups="account.group_account_invoice"/>
                    <button name="action_invoice_proforma2" type="object" states="draft" string="PRO-FORMA" groups="account.group_proforma_invoices"/>
                    <button name="363" type="action" string="Refund Invoice" groups="account.group_account_invoice" attrs="{'invisible': ['|',('type', '=', 'out_refund'), ('state', 'not in', ('open','proforma2','paid'))]}"/>
                    <button name="action_invoice_cancel" type="object" states="draft,proforma2,open" string="Cancel Invoice" groups="base.group_no_one"/>
                    <button name="action_invoice_draft" states="cancel" string="Reset to Draft" type="object" groups="account.group_account_invoice"/>
                    <field name="state" widget="statusbar" nolabel="1" statusbar_visible="draft,open,paid"/>
                </header>
				...
                </form>
            
I tried enabling `Allow Cancelling Entries` on all journals but this didn't have any affect.
After removing `account_cancel` I got a bit further (I think)

	ParseError: "External ID not found in the system: crm_claim.base_menu_aftersale" while parsing /opt/odoo/custom/addons/crm_claim_rma/views/claim_line.xml:171, near
	<menuitem name="Claim lines" id="menu_crm_case_claims_claim_lines" parent="crm_claim.base_menu_aftersale" action="act_crm_case_claim_lines" sequence="2"/>

Which I than changed to:

	    <!-- Menu -->
    <menuitem
            name="Claim lines"
            id="menu_crm_case_claims_claim_lines"
            parent="crm_claim.menu_aftersale"
            action="act_crm_case_claim_lines"
            sequence="2"/>


Then I got:

	Exception: Module loading crm_claim_rma failed: file crm_claim_rma/security/ir.model.access.csv could not be processed:
	 No matching record found for external id 'base.group_sale_salesman_all_leads' in field 'Group'
	 No matching record found for external id 'base.group_sale_salesman_all_leads' in field 'Group'
	 No matching record found for external id 'base.group_sale_manager' in field 'Group'
	 No matching record found for external id 'base.group_sale_manager' in field 'Group'
	 No matching record found for external id 'base.group_sale_salesman' in field 'Group'
	 No matching record found for external id 'base.group_sale_salesman' in field 'Group'

Which i fixed with:

	id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
	access_substate_user_all_leads,substate.substate.user,model_substate_substate,sales_team.group_sale_salesman,1,1,1,0
	access_claim_line_user_all_leads,claim.line.user,model_claim_line,sales_team.group_sale_salesman,1,1,1,0
	access_substate_manager,substate.substate.manager,model_substate_substate,sales_team.group_sale_manager,1,1,1,1
	access_claim_line_manager,claim.line.manager,model_claim_line,sales_team.group_sale_manager,1,1,1,1
	access_substate_user,substate.substate.user,model_substate_substate,sales_team.group_sale_salesman,1,1,1,0
	access_claim_line_user,claim.line.user,model_claim_line,sales_team.group_sale_salesman,1,1,1,0

I Can't find the repository to make the pull request on...

2018-01-11 22:42 UTC, DipSwitch requested changes

2018-01-11 22:42 UTC, DipSwitch commented on crm_claim_rma/__manifest__.py
>                "Odoo Community Association (OCA)",
`,` is in the wrong place

2018-01-11 22:42 UTC, DipSwitch commented on crm_claim_rma/models/claim_line.py
> +        return self.env['product.supplierinfo'].warranty_return_partner
Change this to: `self.env['product.supplierinfo'].fields_get('warranty_return_partner')['warranty_return_partner']['selection']` and you are golden. Will test the rest tomorrow.

2018-01-11 23:14 UTC, DipSwitch commented
wizard/claim_make_picking.py: `s/'name': line.product_id.name_template/'name': line.product_id.name/gi`

@ Line 135 & 235

I however can't change the state of the Claim Line. However this is the first time I'm working with this plugin :p

2018-04-12 05:32 UTC, DipSwitch commented
Any way I can help with this module?

2018-11-19 14:20 UTC, Cedric-Pigeon commented
@max3903 Hi, could you tell me if the PR is usable as this or not ? and eventually what we can do to end it ? Thanks

2018-11-19 14:23 UTC, max3903 commented
@Cedric-Pigeon I don't remember :(

2019-05-23 16:17 UTC, max3903 commented
@Cedric-Pigeon @DipSwitch @flotho I was not able to restart runbot.

I propose you 2 options:
# You can test and review and I fix eventual errors to merge the pull request.
# I close the pull request.

2019-06-03 09:26 UTC, kenvac commented
I am available to offer my help on this task.

2019-06-03 12:17 UTC, rousseldenis commented
@max3903 I've relaunched runbot.
There is a warning when loading crm_claim_rma/data/crm_team.xml :

WARNING openerp_test odoo.models: crm.team.create() includes unknown fields: code

2019-06-03 19:29 UTC, rousseldenis requested changes
LGTM. Some comments

2019-06-03 19:29 UTC, rousseldenis commented on crm_claim_rma/__manifest__.py
> +    # 'test': [
These entries should be removed or test converted

2019-06-03 19:29 UTC, rousseldenis commented on crm_claim_rma/models/claim_line.py
> +    # _rec_name = "display_name"
This should be removed

2019-06-03 19:29 UTC, rousseldenis commented on crm_claim_rma/models/claim_line.py
> +                                # compute='_compute_priority',
This should be removed

2019-06-04 07:25 UTC, rousseldenis approved these changes

2019-06-04 15:20 UTC, kenvac reviewed
All looks good. I have few comments to make.

Change __openerp__.py to __manifest__.py
https://github.com/OCA/rma/blob/6e17197dc7bc8d1be18faf2047ca6f17e45cbde3/crm_claim_rma/wizards/claim_make_picking.xml#L6

Change OpenERP to Odoo
https://github.com/OCA/rma/blob/6e17197dc7bc8d1be18faf2047ca6f17e45cbde3/crm_claim_rma/wizards/claim_make_picking.xml#L3

Do we really need copy method. Can't we use copy=False at fields level? 
https://github.com/OCA/rma/blob/6e17197dc7bc8d1be18faf2047ca6f17e45cbde3/crm_claim_rma/models/claim_line.py#L188

Add _compute_priority to test case
https://github.com/OCA/rma/blob/6e17197dc7bc8d1be18faf2047ca6f17e45cbde3/crm_claim_rma/models/claim_line.py#L200

method _get_subject not used anywhere
https://github.com/OCA/rma/blob/6e17197dc7bc8d1be18faf2047ca6f17e45cbde3/crm_claim_rma/models/claim_line.py#L182

Add set_warranty_limit to test case
https://github.com/OCA/rma/blob/6e17197dc7bc8d1be18faf2047ca6f17e45cbde3/crm_claim_rma/models/claim_line.py#L279

Add method set_warranty to test case
https://github.com/OCA/rma/blob/6e17197dc7bc8d1be18faf2047ca6f17e45cbde3/crm_claim_rma/models/claim_line.py#L372

Add _compute_display_name to test case
https://github.com/OCA/rma/blob/6e17197dc7bc8d1be18faf2047ca6f17e45cbde3/crm_claim_rma/models/claim_line.py#L406

2019-06-25 23:29 UTC, rafaelbn approved these changes

2019-06-25 23:31 UTC, rafaelbn commented
/ocabot merge

2019-06-25 23:33 UTC, max3903 commented
/ocabot merge

2019-06-25 23:50 UTC, merged