[12.0][FIX] rma: RMA quantities are not quantities on hand
OCA/rma pull request #179
Opened 2020-10-31 03:19 UTC by ernestotejeda

cc @Tecnativa TT26542

2020-11-03 12:00 UTC, pedrobaeza requested changes

2020-11-03 12:00 UTC, pedrobaeza commented on rma/hooks.py
> +                active_test=False).create(rma_location_vals).id
This is not correct code. You have to extract the proper value.

2020-11-03 12:00 UTC, pedrobaeza commented on rma/hooks.py
> +        rma_location_vals = warehouse._get_rma_location_values()
Do this only in case you need it (inside the if).

2020-11-03 20:20 UTC, pedrobaeza approved these changes

2020-11-04 08:34 UTC, chienandalu approved these changes

2020-11-04 08:37 UTC, pedrobaeza commented
/ocabot merge patch

2020-11-04 09:26 UTC, merged