[17.0][IMP] RMA - refactor to use procurement run
OCA/rma pull request #397
Opened 2024-06-25 07:25 UTC by victoralmau

FWP from 16.0: https://github.com/OCA/rma/pull/392

Extra changes:
- Change reception_move_ids to reception_move_id
- Add test_rma_replace_pick_ship
- Code and method reduction to simplify logic
- Set route_ids (in/out) from procurements

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT48789

2024-06-26 15:51 UTC, chienandalu requested changes

2024-06-26 15:51 UTC, chienandalu commented on rma/models/stock_picking.py
> +        rma = self.move_lines.mapped("rma_ids")
```suggestion
        rma = self.move_ids.mapped("rma_ids")
```

2024-06-26 15:53 UTC, pedrobaeza commented on rma/models/stock_picking.py
> +        rma = self.move_lines.mapped("rma_ids")
In fact:

```suggestion
        rma = self.move_ids.rma_ids
```

2024-06-27 06:19 UTC, chienandalu approved these changes
:+1:

2024-06-27 18:29 UTC, pedrobaeza commented
Testing in the runboat http://oca-rma-17-0-pr397-605691345d56.runboat.odoo-community.org to return a delivery order marking the RMA option, I get:

![imagen](https://github.com/OCA/rma/assets/7165771/549d0b28-8f92-4622-b02a-3fe7486ab873)

2024-06-28 10:32 UTC, victoralmau commented
Reviewing the error you indicate, I see that it is a side effect of something that already happens currently in v17, if the user does NOT have the locations permission, the picking that is created does NOT have the correct data (location and picking_type_id).

This does not happen in tests because the user that is used does have this permission, I will review it to fix it.

2024-07-01 22:37 UTC, pedrobaeza approved these changes
/ocabot merge major

2024-07-01 22:47 UTC, merged